CREATE TABLE PEDIDO(
	ID_PEDIDO SERIAL,
	NUMERO INTEGER,
	DESCRICAO VARCHAR(100),
	TOTAL REAL,
	QTDE INTEGER,
	CLIENTE VARCHAR(50),
	ID_PRODUTO SERIAL
);

CREATE TABLE PRODUTO(
	ID_PRODUTO SERIAL,
	CODIGO INTEGER,
	DESCRICAO VARCHAR(100),
	VALOR REAL
);

CREATE TABLE MESA(
	ID_MESA SERIAL,
	QTDE_PERNAS INTEGER,
	DS_MATERIAL VARCHAR(25),
	NUM_ALTURA REAL,
	NUM_COMPRIMENTO REAL,
	NUM_LARGURA REAL,
	FABRICANTE VARCHAR(100),
	DS_FORMATO VARCHAR(50)
);