CREATE TABLE centros (id_centro SERIAL NOT NULL, nome varchar(100), sigla varchar(10), localizacao varchar(100), diretor varchar(100), PRIMARY KEY (id_centro));
CREATE TABLE departamentos (id_departamento SERIAL NOT NULL, nome varchar(100), sigla varchar(10), centro_id INT, PRIMARY KEY (id_departamento));
CREATE TABLE cursos (id_curso SERIAL NOT NULL, nome varchar(100), duracao INT, departamento_id INT, tipo varchar(50), PRIMARY KEY (id_curso));
CREATE TABLE professores (id_professor SERIAL NOT NULL, nome varchar(100), titulacao varchar(50), email varchar(100), curso_id INT, PRIMARY KEY (id_professor));
CREATE TABLE disciplinas (id_disciplina SERIAL NOT NULL, nome varchar(100), carga_horaria INT, curso_id INT, professor_id INT, PRIMARY KEY (id_disciplina));
CREATE TABLE salas (id_sala SERIAL NOT NULL, nome varchar(50), capacidade INT, localizacao varchar(100), PRIMARY KEY (id_sala));
CREATE TABLE turmas (id_turma SERIAL NOT NULL, disciplina_id INT, sala_id INT, horario varchar(50), semestre varchar(20), PRIMARY KEY (id_turma));
CREATE TABLE alunos (id_aluno SERIAL NOT NULL, nome varchar(100), matricula varchar(20) UNIQUE, email varchar(100), curso_id INT, PRIMARY KEY (id_aluno));
CREATE TABLE funcionarios (id_funcionario SERIAL NOT NULL, nome varchar(100), cargo varchar(50), email varchar(100), departamento_id INT, PRIMARY KEY (id_funcionario));
CREATE TABLE alunos_turmas (id_aluno INT NOT NULL, id_turma INT NOT NULL, PRIMARY KEY (id_aluno, id_turma));
ALTER TABLE departamentos ADD CONSTRAINT FKdepartamen563445 FOREIGN KEY (centro_id) REFERENCES centros (id_centro);
ALTER TABLE cursos ADD CONSTRAINT FKcursos998211 FOREIGN KEY (departamento_id) REFERENCES departamentos (id_departamento);
ALTER TABLE professores ADD CONSTRAINT FKprofessore621432 FOREIGN KEY (curso_id) REFERENCES cursos (id_curso);
ALTER TABLE disciplinas ADD CONSTRAINT FKdisciplina989896 FOREIGN KEY (curso_id) REFERENCES cursos (id_curso);
ALTER TABLE disciplinas ADD CONSTRAINT FKdisciplina842467 FOREIGN KEY (professor_id) REFERENCES professores (id_professor);
ALTER TABLE turmas ADD CONSTRAINT FKturmas519344 FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id_disciplina);
ALTER TABLE turmas ADD CONSTRAINT FKturmas958335 FOREIGN KEY (sala_id) REFERENCES salas (id_sala);
ALTER TABLE alunos ADD CONSTRAINT FKalunos197587 FOREIGN KEY (curso_id) REFERENCES cursos (id_curso);
ALTER TABLE funcionarios ADD CONSTRAINT FKfuncionari200686 FOREIGN KEY (departamento_id) REFERENCES departamentos (id_departamento);
ALTER TABLE alunos_turmas ADD CONSTRAINT FKalunos_tur177631 FOREIGN KEY (id_aluno) REFERENCES alunos (id_aluno);
ALTER TABLE alunos_turmas ADD CONSTRAINT FKalunos_tur378073 FOREIGN KEY (id_turma) REFERENCES turmas (id_turma);
