ALTER TABLE PRODUTO ADD COLUMN DESCRICAO3 TEXT check (descricao3<>'');
ALTER TABLE PRODUTO DROP COLUMN DESCRICAO;
ALTER TABLE PRODUTO ADD CHECK (NOME<>'');
ALTER TABLE PRODUTO ADD CONSTRAINT NOME_RESTRICAO UNIQUE (PRODUTO_NUM);
ALTER TABLE PRODUTO ADD FOREIGN KEY (ID_PRODUTO_GRUPO) REFERENCES PRODUTO_GRUPO;
ALTER TABLE PRODUTO ALTER COLUMN PRODUTO_NUM SET NOT NULL;

ALTER TABLE produto ALTER COLUMN PRECO SET DEFAULT 7.77
ALTER TABLE produto ALTER COLUMN PRECO DROP DEFAULT

ALTER TABLE PRODUTO ALTER COLUMN PRECO TYPE NUMERIC

ALTER TABLE PRODUTO RENAME COLUMN PRODUTO_NUM TO PRODUTO_NUMERO

ALTER TABLE produto RENAME TO ITENS