DROP TABLE IF EXISTS PED_PROD;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS CONDICAO_PAGAMENTO;
DROP TABLE IF EXISTS PRECO;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE(
	ID_CLIENTE SERIAL PRIMARY KEY,
	NM_CLIENTE VARCHAR(100),
	DT_NASCIMENTO DATE,
	DS_SEXO VARCHAR(10),
	CPF VARCHAR(14)
);


CREATE TABLE PRECO(
	ID_PRECO SERIAL PRIMARY KEY,
	VL_PRECO NUMERIC,
	QTDE_USADO INTEGER,
	DT_CADASTRO DATE,
	DESCRICAO TEXT
);

CREATE TABLE CONDICAO_PAGAMENTO(
	ID_CONDICAO_PAGAMENTO SERIAL PRIMARY KEY,
	NM_CONDICAO_PAGAMENTO VARCHAR(50),
	VL_JUROS NUMERIC,
	DT_CADASTRO DATE,
	DT_ATUALIZADO DATE
);


CREATE TABLE PEDIDO (
	ID_PEDIDO SERIAL PRIMARY KEY,
	DT_CADASTRO DATE,
	ID_CLIENTE INTEGER,
	NM_COLABORADOR VARCHAR(100),
	VL_PEDIDO NUMERIC,
	ID_CONDICAO_PAGAMENTO INTEGER,
	DS_CIDADE VARCHAR(100),
	QTDE_PARCELAS INTEGER,
	DESCRICAO VARCHAR(100),
	TIPO_PEDIDO VARCHAR(100),
	
	FOREIGN  KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN  KEY(ID_CONDICAO_PAGAMENTO) REFERENCES CONDICAO_PAGAMENTO(ID_CONDICAO_PAGAMENTO)
	
);

CREATE TABLE PRODUTO(
	ID_PRODUTO SERIAL PRIMARY KEY,
	NM_PRODUTO VARCHAR(100),
	ID_PRECO INTEGER,
	TEMPO_PERESSIVEL NUMERIC,
	DS_MARCA VARCHAR(100),
	DS_VERSAO VARCHAR(100),
	VL_VOLUME NUMERIC,
	VL_PESO NUMERIC,
	DS_FORNECEDOR VARCHAR(100),
	DT_ATUALIZADO DATE,
	
	FOREIGN  KEY (ID_PRECO) REFERENCES PRECO(ID_PRECO)
);

CREATE TABLE PED_PROD(
	ID_PED_PROD SERIAL PRIMARY KEY,
	ID_PEDIDO INTEGER,
	ID_PRODUTO INTEGER,
	DT_CADASTRO DATE,
	FLAG_PAGO INTEGER,
	
	FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);


INSERT INTO CLIENTE (NM_CLIENTE, DT_NASCIMENTO, DS_SEXO, CPF)
VALUES 
('JOOOOOAQUIMMM', '2000-09-03', 'MACHO', '11111111111111'),
('ANANNANANAN', '2021-08-02', 'MUIE', '22222222222222'),
('PEDROOOOOOOOOOOOO', '2001-10-30', 'MACHO', '33333333333333'),
('BERNALODIM', '2004-03-29', 'MACHO', '44444444444444'),
('GESTRUDESSSSSS', '2006-05-08', 'MUIE', '55555555555555'),
('CARLÃO DO TREM', '1989-01-15', 'MACHO', '66666666666666'),
('FILOMENALINA', '1993-07-19', 'MUIE', '77777777777777'),
('ZEZIM DA FUBÁ', '1980-11-11', 'MACHO', '88888888888888'),
('TIÃO PINGA RUIM', '1972-04-21', 'MACHO', '99999999999999'),
('DONA CHICA POWER', '1965-05-23', 'MUIE', '10101010101010'),
('TOINZIM DO PEIXE', '1995-08-08', 'MACHO', '11122233344455'),
('MANGUINHA SILVA', '2002-09-09', 'MACHO', '66677788899900'),
('BIGUINHO LOKO', '1997-06-15', 'MACHO', '12345678901234'),
('GERONCINHA SUPLEX', '1991-03-18', 'MUIE', '98765432109876'),
('NERVALDOSSAURUS', '2005-02-28', 'MACHO', '11223344556677'),
('DOROTHEA MENDONZINHA', '1986-10-10', 'MUIE', '99887766554433'),
('SORVETEIRO MALUCO', '1998-12-12', 'MACHO', '12312312312312'),
('PASTA LAVANDA', '1990-11-14', 'MUIE', '32132132132132'),
('ZEZÃO ZUNZUN', '1979-01-20', 'MACHO', '65465465465465'),
('CREONCINHA BOLD', '2003-04-04', 'MUIE', '76576576576576');


INSERT INTO PRECO (VL_PRECO, QTDE_USADO, DT_CADASTRO, DESCRICAO)
VALUES
(199.99, 2, CURRENT_DATE, 'PREÇO JUSTO... SÓ QUE NÃO'),
(0.01, 0, CURRENT_DATE, 'PROMOÇÃO DE CENTAVO!!!'),
(1500.50, 5, CURRENT_DATE, 'VALOR DE CARRO POPULAR'),
(9.99, 10, CURRENT_DATE, 'PREÇO DE UMA COXINHA GOURMET'),
(1000000.00, 1, CURRENT_DATE, 'PREÇO DE MANSÃO DE FAMOSO'),
(0.50, 100, CURRENT_DATE, 'PREÇO DE PECHINCHA'),
(250.75, 7, CURRENT_DATE, 'VALOR DE PRESENTE PRA SOGRA'),
(3.33, 15, CURRENT_DATE, 'VALOR MÍSTICO'),
(999.99, 1, CURRENT_DATE, 'VALOR REDONDO MAS EXAGERADO'),
(49.99, 20, CURRENT_DATE, 'PRATICAMENTE DE GRAÇA');


INSERT INTO CONDICAO_PAGAMENTO (NM_CONDICAO_PAGAMENTO, VL_JUROS, DT_CADASTRO, DT_ATUALIZADO)
VALUES
('PAGAMENTO COM MIOSÓTIS', 0.25, CURRENT_DATE, CURRENT_DATE),
('CARTÃO DOS SONHOS', 1.75, CURRENT_DATE, CURRENT_DATE),
('DÉBITO DIRETO DA ALMA', 0, CURRENT_DATE, CURRENT_DATE),
('CARTÃO DE CRÉDITO ASTRAL', 2.5, CURRENT_DATE, CURRENT_DATE),
('PIX DO FUTURO', 0, CURRENT_DATE, CURRENT_DATE),
('FINANCIAMENTO DE VIDA', 99.9, CURRENT_DATE, CURRENT_DATE),
('TRANSFERÊNCIA INTERDIMENSIONAL', 0.5, CURRENT_DATE, CURRENT_DATE),
('BOLETO SEM VOLTA', 3.5, CURRENT_DATE, CURRENT_DATE),
('CHEQUE FANTASMA', 1.25, CURRENT_DATE, CURRENT_DATE),
('PAGAMENTO POR CANTORIA', 0, CURRENT_DATE, CURRENT_DATE),
('PAGAMENTO DOIDO D+', 0, CURRENT_DATE, CURRENT_DATE);


INSERT INTO PEDIDO (DT_CADASTRO, ID_CLIENTE, NM_COLABORADOR, VL_PEDIDO, ID_CONDICAO_PAGAMENTO, DS_CIDADE, QTDE_PARCELAS, DESCRICAO, TIPO_PEDIDO)
VALUES
(CURRENT_DATE, 1, 'ZÉ DAS COUVES', 150.75, 1, 'Pindaíba', 3, 'PEDIDO DE COUVE', 'ORDINÁRIO'),
(CURRENT_DATE, 2, 'JÃO DO PÃO', 300.10, 2, 'Farinhópolis', 5, 'COMPRA DE PÃO', 'EXTRAORDINÁRIO'),
(CURRENT_DATE, 3, 'MARIA DA FEIRA', 499.99, 3, 'Frescalândia', 6, 'COMPRA DE VEGETAIS', 'SINGULAR'),
(CURRENT_DATE, 4, 'TONHO DO CARVÃO', 1000.99, 4, 'Brasópolis', 12, 'PEDIDO QUENTE', 'SÓ NA BRASA'),
(CURRENT_DATE, 5, 'DONA FOFOCA', 799.99, 5, 'Mexericópolis', 10, 'FALATÓRIO', 'DISCRETO'),
(CURRENT_DATE, 6, 'PÉ DE CHINELO', 299.50, 6, 'Sandalinha', 2, 'PEDIDO COM PÉ', 'CALÇADO'),
(CURRENT_DATE, 7, 'ZÉ BOIADEIRO', 200.25, 7, 'Boiobá', 3, 'COMPRA DE GADO', 'RURAL'),
(CURRENT_DATE, 8, 'JÚLIA DO DOCE', 500.75, 8, 'Doçurândia', 4, 'AÇÚCAR PURINHO', 'GOSTOSO'),
(CURRENT_DATE, 9, 'MARICOTA', 299.99, 9, 'Crocantópolis', 2, 'PEDIDO CROQUETE', 'MOLHADINHO'),
(CURRENT_DATE, 10, 'XUXU BALA', 800.45, 10, 'Pinga-Limão', 7, 'ENCOMENDA LÍQUIDA', 'BEBIDA'),
(CURRENT_DATE, 1, 'TIO PATINHAS', 1000000.00, 1, 'Riquezópolis', 1, 'PEDIDO DE OURO', 'LUXUOSO'),
(CURRENT_DATE, 2, 'XIS DO DINHEIRO', 500.00, 2, 'Capitalândia', 12, 'DINHEIRO VIVO', 'SUAVE'),
(CURRENT_DATE, 3, 'ANA DA LUA', 300.20, 3, 'Fazendópolis', 5, 'LUA CHEIA', 'LUNÁTICO'),
(CURRENT_DATE, 4, 'ZÉ DA PADARIA', 120.50, 4, 'Padocópolis', 1, 'PÃO QUENTINHO', 'NORMAL'),
(CURRENT_DATE, 5, 'CHICO DA BOLA', 999.99, 5, 'Esportópolis', 3, 'PEDIDO ESPORTIVO', 'ATIVO'),
(CURRENT_DATE, 6, 'RITA DA CARNE', 200.30, 6, 'Churrasquim', 2, 'COMPRA DE CHURRASCO', 'SABOROSO'),
(CURRENT_DATE, 7, 'ZILDA COSTUREIRA', 150.00, 7, 'Moda Fashion', 1, 'PEDIDO DE ROUPA', 'ELEGANTE'),
(CURRENT_DATE, 8, 'BIA DA FÁBRICA', 3000.00, 8, 'Indústria Forte', 8, 'ENCOMENDA INDUSTRIAL', 'ROBUSTO'),
(CURRENT_DATE, 9, 'TONY DO MERCADO', 450.50, 9, 'Mercadolândia', 2, 'COMPRA NO MERCADO', 'SIMPLÃO'),
(CURRENT_DATE, 10, 'JÃO DO BRASIL', 750.00, 10, 'Brasópolis', 4, 'PEDIDO PATRIÓTICO', 'NACIONAL');


INSERT INTO PRODUTO (NM_PRODUTO, ID_PRECO, TEMPO_PERESSIVEL, DS_MARCA, DS_VERSAO, VL_VOLUME, VL_PESO, DS_FORNECEDOR, DT_ATUALIZADO)
VALUES
('PRODUTO CABULOSO 11', 1, 5, 'MARCA MISTERIOSA', 'VERSAO Q', 4.5, 5.5, 'FORNECEDOR MAGALY', CURRENT_DATE),
('PRODUTO INOVADOR 12', 2, 3, 'MARCA FUTURISTA', 'VERSAO NEO', 2.1, 3.6, 'FORNECEDOR ROBERTO', CURRENT_DATE),
('PRODUTO BOLADÃO 13', 3, 6, 'MARCA FORTE', 'VERSAO EXTREME', 3.2, 4.8, 'FORNECEDOR MILENA', CURRENT_DATE),
('PRODUTO TERROR 14', 4, 9, 'MARCA SOMBRIA', 'VERSAO DARK', 1.7, 2.2, 'FORNECEDOR GERSON', CURRENT_DATE),
('PRODUTO MANJADO 15', 5, 7, 'MARCA TRADICIONAL', 'VERSAO LEGACY', 6.2, 7.3, 'FORNECEDOR ANINHA', CURRENT_DATE),
('PRODUTO SUPREMO 16', 6, 4, 'MARCA SUPREMA', 'VERSAO ULTIMATE', 2.9, 3.4, 'FORNECEDOR LUIZ', CURRENT_DATE),
('PRODUTO INCRÍVEL 17', 7, 5, 'MARCA SURPREENDENTE', 'VERSAO WOW', 4.4, 5.8, 'FORNECEDOR CLAUDIO', CURRENT_DATE),
('PRODUTO EXTREMO 18', 8, 8, 'MARCA TOPZEIRA', 'VERSAO SUPER', 3.6, 4.1, 'FORNECEDOR VICTOR', CURRENT_DATE),
('PRODUTO POTENTE 19', 9, 2, 'MARCA TURBINADA', 'VERSAO TURBO', 6.5, 7.8, 'FORNECEDOR LARA', CURRENT_DATE),
('PRODUTO EXPLOSIVO 20', 10, 10, 'MARCA DYNAMITE', 'VERSAO BANG', 5.2, 6.0, 'FORNECEDOR HUGO', CURRENT_DATE),
('PRODUTO AVASSALADOR 21', 1, 3, 'MARCA DEMOLIDORA', 'VERSAO CRUSH', 7.0, 8.5, 'FORNECEDOR DAIANE', CURRENT_DATE),
('PRODUTO IMPARÁVEL 22', 2, 6, 'MARCA VELOZ', 'VERSAO ZOOM', 4.7, 5.1, 'FORNECEDOR FERNANDO', CURRENT_DATE),
('PRODUTO CAMPEÃO 23', 3, 5, 'MARCA DOS DEUSES', 'VERSAO GOLD', 5.0, 6.5, 'FORNECEDOR RUI', CURRENT_DATE),
('PRODUTO DIVINO 24', 4, 4, 'MARCA ETERNA', 'VERSAO INFINITY', 6.3, 7.7, 'FORNECEDOR CARLA', CURRENT_DATE),
('PRODUTO GALÁCTICO 25', 5, 9, 'MARCA COSMOS', 'VERSAO ASTRO', 3.8, 4.9, 'FORNECEDOR ANDRÉ', CURRENT_DATE),
('PRODUTO CRIATIVO 26', 6, 2, 'MARCA ARTÍSTICA', 'VERSAO ARTE', 5.4, 6.1, 'FORNECEDOR RAFAEL', CURRENT_DATE),
('PRODUTO FANTÁSTICO 27', 7, 1, 'MARCA MÁGICA', 'VERSAO FANTASIA', 4.2, 5.3, 'FORNECEDOR BRUNA', CURRENT_DATE),
('PRODUTO FEROZ 28', 8, 3, 'MARCA BRAVURA', 'VERSAO TIGRE', 7.2, 8.0, 'FORNECEDOR LUIZA', CURRENT_DATE),
('PRODUTO DO FUTURO 29', 9, 6, 'MARCA TECH', 'VERSAO FUTURE', 5.6, 6.9, 'FORNECEDOR MIGUEL', CURRENT_DATE),
('PRODUTO AVANÇADO 30', 10, 8, 'MARCA INOVAÇÃO', 'VERSAO NEXT', 6.8, 7.2, 'FORNECEDOR MANUEL', CURRENT_DATE);


INSERT INTO PED_PROD (ID_PEDIDO, ID_PRODUTO, DT_CADASTRO, FLAG_PAGO)
VALUES
(1, 1, CURRENT_DATE, 1),
(1, 2, CURRENT_DATE, 0),
(2, 3, CURRENT_DATE, 1),
(2, 4, CURRENT_DATE, 1),
(3, 5, CURRENT_DATE, 0),
(3, 6, CURRENT_DATE, 1),
(4, 7, CURRENT_DATE, 1),
(4, 8, CURRENT_DATE, 0),
(5, 9, CURRENT_DATE, 1),
(5, 10, CURRENT_DATE, 0),
(6, 11, CURRENT_DATE, 1),
(6, 12, CURRENT_DATE, 1),
(7, 13, CURRENT_DATE, 0),
(7, 14, CURRENT_DATE, 1),
(8, 15, CURRENT_DATE, 1),
(8, 16, CURRENT_DATE, 0),
(9, 17, CURRENT_DATE, 1),
(9, 18, CURRENT_DATE, 1),
(10, 19, CURRENT_DATE, 0);

SELECT 
	*
FROM pedido
WHERE id_cliente = (SELECT id_cliente FROM cliente WHERE nm_cliente = 'JOOOOOAQUIMMM' )

SELECT * FROM cliente c 

SELECT * FROM cliente c WHERE NOT EXISTS (SELECT id_cliente FROM cliente c2  WHERE nm_cliente = 'Pedro')

SELECT * FROM condicao_pagamento cp WHERE id_condicao_pagamento  IN (SELECT id_condicao_pagamento FROM pedido p)

SELECT * FROM condicao_pagamento cp WHERE id_condicao_pagamento  NOT IN (SELECT id_condicao_pagamento FROM pedido p)

SELECT * FROM condicao_pagamento cp WHERE id_condicao_pagamento ALL (SELECT id_condicao_pagamento FROM pedido p)

SELECT * FROM condicao_pagamento cp WHERE id_condicao_pagamento <> (SELECT id_condicao_pagamento FROM pedido LIMIT 1)